name: radar-rt-validation
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - geopy
  - pip
  - pip:
    - pandas
    - matplotlib
    - seaborn
    - requests
    - sklearn
    - xlsxwriter
    - seaborn-qqplot